config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  resources :tasks, except: [:index]
end

app/models/task.rb
class Task < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @tasks = Task.all
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def new
    @task = Task.new
  end
  def create
    @task = Task.create(task_params)
    @tasks = Task.all
  end
  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    @tasks = Task.all
  end
  def update
    @task = Task.find(params[:id])
    @task.update_attributes(status_params)
    @tasks = Task.all
  end
  private
  def task_params
    params.require(:task).permit(:title, :details)
  end
  def status_params
    params.permit(:title, :details, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Todo
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .row-fluid
      .span10.offset1
        .hero-unit.text-center
          %h1
            Track, Organize Derp's Objectives
          %br
          %p
            A simple ToDo application inspired by #{ link_to 'arubystory.com', 'http://www.arubystory.com'}
          = link_to 'New ToDo', new_task_path, class: 'btn btn-primary', remote: true
        = yield

app/views/pages/home.html.haml
#task-list.container
  = render partial: 'tasks/task_list', locals: {tasks: @tasks}
#modal.modal.fade

app/views/tasks/_task_form.html.haml
.modal-header
  %h1 New Task
= simple_form_for task, class: 'clearfix', remote: true do |f|
  .modal-body
    = f.input :title
    = f.input :details
  .modal-footer
    = f.submit 'Save', class: 'btn btn-primary'

app/views/tasks/_task_list.html.haml
- if tasks.empty?
  %span.text-warning No tasks!
- else
  %table.table.table-hover.table-bordered
    %thead
      %tr
        %th Title
        %th Details
        %th Status
        %th Actions
    %tbody
      - tasks.each do |task|
        %tr
          %td
            %strong= task.title
          %td.text-info= task.details
          %td.text-info= task.status
          %td
            - if task.status == "Done"
              = link_to task_path(task, {:status => "Redo"}), :method => :patch, :title => "Redo", :remote => true do
                %i.icon-repeat
            - else
              = link_to task_path(task, {:status => "Done"}), :method => :patch, :title => "Done", :remote => true do
                %i.icon-ok-circle
            = link_to task_path(task), :method => :delete, data: {confirm: "Are you sure you want to delete task #{task.title}?"}, :title => "Delete", :remote => true do
              %i.icon-trash

app/views/tasks/create.js.erb
$('#task-list').html('<%= j(render partial: 'tasks/task_list', locals: {tasks: @tasks}) %>');
$('#modal').modal('hide');

app/views/tasks/destroy.js.erb
$('#task-list').html('<%= j(render partial: 'task_list', locals: {tasks: @tasks}) %>');
$('#modal').modal('hide');

app/views/tasks/new.js.erb
m = $('#modal');
m.html('<%= j(render partial: 'task_form', locals: {task: @task}) %>');
m.modal('show');

app/views/tasks/update.js.erb
$('#task-list').html('<%= j(render partial: 'task_list', locals: {tasks: @tasks})%>');
$('#modal').modal('hide');